version: '3'

services:
  app:
    build: .
    restart: always
    env_file: .env
    ports:
      - "${EXT_PORT}:80"
    volumes:
      - ./data/media:/app/media
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    logging: &logging
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    environment:
      PRODUCTION_ENV: 1

  postgres:
    image: postgres:10.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${POSTGRES_EXT_PORT}:5432"
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    logging: *logging

  redis:
    image: redis:4.0.9-alpine
    restart: always
    volumes:
      - './data/redis:/data'

  redis-cache:
    image: redis:4.0.9-alpine
    restart: always
    volumes:
      - ./conf/redis/redis_cache.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
