# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата/время публикации')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата/время истечения')),
                ('code', models.TextField(verbose_name='Код баннера')),
            ],
            options={
                'verbose_name_plural': 'Баннеры',
                'verbose_name': 'Баннер',
            },
        ),
        migrations.CreateModel(
            name='BannerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('title', models.CharField(max_length=225, verbose_name='Название баннерного места')),
                ('banner_id', models.CharField(help_text='допустимы латинские буквы, цифры, либо символ "_"', max_length=150, unique=True, verbose_name='Идентификатор баннера')),
            ],
            options={
                'verbose_name_plural': 'Типы баннеров',
                'verbose_name': 'Тип баннера',
            },
        ),
    ]
