# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_banner_banner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(default=1, max_length=225, verbose_name='Название баннера'),
            preserve_default=False,
        ),
    ]
