# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_banner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='code',
            field=models.TextField(help_text='Могут быть использованы от одного до десяти случайных чисел с именами #RANDOM<номер>#', verbose_name='Код баннера'),
        ),
    ]
