# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('banners', '0004_auto_20171221_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageRelate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='ScriptItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField(choices=[(0, 'HEAD'), (1, 'FOOTER')], verbose_name='Вставить в')),
                ('rule', models.SmallIntegerField(choices=[(0, 'Вставить в страницы'), (1, 'Исключить страницы')], verbose_name='Правила вставки')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Скрипт',
                'verbose_name_plural': 'Скрипты',
            },
        ),
        migrations.CreateModel(
            name='ScriptItems',
            fields=[
                ('pagerelate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banners.PageRelate')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('related_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='banners.ScriptItem')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('banners.pagerelate', models.Model),
        ),
        migrations.AddField(
            model_name='pagerelate',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.Page', verbose_name='Страница'),
        ),
    ]
