# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0006_auto_20180508_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptitem',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
