# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0008_scriptitem_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptitem',
            name='platform',
            field=models.SmallIntegerField(choices=[(0, 'Мобильная'), (1, 'Десктоп'), (2, 'Все')], default=2, verbose_name='Платформа'),
        ),
    ]
