# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0010_banner_last_modifed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptitem',
            name='last_modifed_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
