# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-18 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0011_scriptitem_last_modifed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptitem',
            name='position',
            field=models.SmallIntegerField(choices=[(0, 'HEAD'), (1, 'FOOTER'), (2, 'BEFORE ARTICLE CONTENT'), (3, 'AFTER ARTICLE CONTENT')], verbose_name='Вставить в'),
        ),
    ]
