# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-06 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0012_auto_20181018_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptitem',
            name='exclude_from_promo',
            field=models.BooleanField(default=False, verbose_name='Исключить из статей, имеющие отношения к промо'),
        ),
    ]
