# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 12:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.wagtailroutablepage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('answer', models.TextField(max_length=1000, null=True, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ExpertIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Страница экспертов',
                'verbose_name_plural': 'Страницы экспертов',
            },
            bases=(wagtail.contrib.wagtailroutablepage.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='ExpertPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('section', models.SmallIntegerField(choices=[(0, 'Красота'), (1, 'Здоровое питание'), (2, 'Фитнес'), (3, 'Секс и любовь'), (4, 'Здоровье глаз'), (5, 'Здоровье')], db_index=True, default=0, verbose_name='Тема')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Описание')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image', verbose_name='Изображение')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='expert_page', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Страница эксперта',
                'verbose_name_plural': 'Страницы эксперта',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.SmallIntegerField(choices=[(0, 'Красота'), (1, 'Здоровое питание'), (2, 'Фитнес'), (3, 'Секс и любовь'), (4, 'Здоровье глаз'), (5, 'Здоровье')], db_index=True, default=0, verbose_name='Тема')),
                ('title', models.CharField(max_length=150, verbose_name='Краткий вопрос')),
                ('text', models.TextField(max_length=1000, verbose_name='Подробнее')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.AddField(
            model_name='answerpage',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='experts.Question', verbose_name='Вопрос'),
        ),
    ]
