# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0002_auto_20171212_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerpage',
            name='section',
            field=models.SmallIntegerField(choices=[(0, 'Красота'), (1, 'Здоровое питание'), (2, 'Фитнес'), (3, 'Секс и любовь'), (4, 'Здоровье глаз'), (5, 'Здоровье')], db_index=True, default=0, verbose_name='Тема'),
        ),
    ]
