# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0003_answerpage_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerpage',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterField(
            model_name='answerpage',
            name='answer',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Ответ'),
        ),
    ]
