# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-15 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0006_auto_20171215_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertpage',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
