# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0007_expertpage_old_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerpage',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
