# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0008_answerpage_old_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerpage',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата/время публикации'),
        ),
    ]
