# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 13:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0009_answerpage_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerpage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
