# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0012_auto_20180404_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertpage',
            name='short_description',
            field=models.CharField(max_length=150, null=True, verbose_name='Регалии'),
        ),
    ]
