# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0013_expertpage_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertpage',
            name='intro',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Интро'),
        ),
    ]
