# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0014_expertpage_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertpage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.CustomImage', verbose_name='Изображение'),
        ),
    ]
