# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0016_auto_20180424_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertpage',
            name='ajax_line_counter',
            field=models.SmallIntegerField(default=5, verbose_name='Количество подгружаемых линий'),
        ),
    ]
