# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0017_expertpage_ajax_line_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertpage',
            name='ajax_line_counter',
        ),
    ]
