# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_staticpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticpage',
            options={'verbose_name': 'Статическая страница', 'verbose_name_plural': 'Статические страницы'},
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Тело страницы'),
        ),
    ]
