# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-22 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20181011_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Активность', 'verbose_name_plural': 'Активности'},
        ),
        migrations.AddField(
            model_name='activitylog',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата обновления'),
            preserve_default=False,
        ),
    ]
