# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20171211_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
