# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0004_auto_20171212_2034'),
        ('community', '0004_comment_old_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='expert_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='experts.AnswerPage'),
        ),
    ]
