# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-17 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_auto_20180417_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='rating',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
