# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('content', '0047_auto_20180412_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='KamasutraIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Страница камасутры',
                'verbose_name_plural': 'Страница камасутры',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='KamasutraPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.RichTextField(null=True, verbose_name='Текст')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата/время публикации')),
                ('preview_picture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.CustomImage', verbose_name='Основная иллюстрация')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
