# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KamasutraPositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
            },
        ),
        migrations.AddField(
            model_name='kamasutrapage',
            name='positions',
            field=models.ManyToManyField(to='specials.KamasutraPositions', verbose_name='Вариант позы'),
        ),
    ]
