# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0002_auto_20180412_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kamasutrapage',
            options={'verbose_name': 'Поза', 'verbose_name_plural': 'Позы'},
        ),
        migrations.AlterModelOptions(
            name='kamasutrapositions',
            options={'verbose_name': 'Вид позы', 'verbose_name_plural': 'Виды поз'},
        ),
        migrations.AlterField(
            model_name='kamasutrapage',
            name='positions',
            field=models.ManyToManyField(help_text='Удерживайте "Control" (или "Command" на Mac), чтобы выбрать несколько значений.', to='specials.KamasutraPositions', verbose_name='Вариант позы'),
        ),
        migrations.AlterField(
            model_name='kamasutrapositions',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
