# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 18:04
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0003_auto_20180412_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kamasutrapage',
            name='positions',
            field=modelcluster.fields.ParentalManyToManyField(help_text='Удерживайте "Control" (или "Command" на Mac), чтобы выбрать несколько значений.', related_name='pages', to='specials.KamasutraPositions', verbose_name='Вариант позы'),
        ),
    ]
