# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0004_auto_20180412_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kamasutrapositions',
            options={'verbose_name': 'Вариант позы', 'verbose_name_plural': 'Варианты поз'},
        ),
    ]
