# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0005_auto_20180412_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamasutraindex',
            name='description',
            field=models.CharField(default=1, max_length=150, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
