# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0006_kamasutraindex_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kamasutraindex',
            old_name='description',
            new_name='short_lead',
        ),
    ]
