# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0007_auto_20180412_1817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KamasutraPositions',
            new_name='KamasutraPosition',
        ),
    ]
