# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
