# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_blogcategory_old_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='preview_picture',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image', verbose_name='Основная иллюстрация'),
        ),
    ]
