# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20171211_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='full_lead',
            field=models.TextField(blank=True, help_text='До 250 символов', max_length=300, null=True, verbose_name='Полный лид'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='short_lead',
            field=models.TextField(help_text='До 160 символов', max_length=300, verbose_name='Короткий лид'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='full_lead',
            field=models.TextField(blank=True, help_text='До 250 символов', max_length=300, null=True, verbose_name='Полный лид'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='short_lead',
            field=models.TextField(help_text='До 160 символов', max_length=300, verbose_name='Короткий лид'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='full_lead',
            field=models.TextField(blank=True, help_text='До 250 символов', max_length=300, null=True, verbose_name='Полный лид'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='short_lead',
            field=models.TextField(help_text='До 160 символов', max_length=300, verbose_name='Короткий лид'),
        ),
    ]
