# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 03:03
from __future__ import unicode_literals

from django.utils import timezone
from django.db import migrations
from itertools import chain
import json

def migrate_published_dates(apps, schema_editor):
    article_pages = apps.get_model('content', 'ArticlePage').objects.all()
    news_pages = apps.get_model('content', 'NewsPage').objects.all()
    blog_pages = apps.get_model('content', 'BlogPage').objects.all()

    for page in chain(article_pages, news_pages, blog_pages):
        page.published_at = page.go_live_at
        page.go_live_at = None
        page.save()
        revision = page.revisions.order_by('-created_at', '-id').first()
        if not revision:
            continue
        content_json = json.loads(revision.content_json)
       
        content_json["published_at"] = str(page.published_at)
        try:
            del content_json["go_live_at"]
        except:
            pass
        revision.content_json = json.dumps(content_json)

        revision.save()
        

class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20180112_0254'),
    ]

    operations = [
        migrations.RunPython(migrate_published_dates),
    ]
