# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20180112_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата/время публикации'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата/время публикации'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата/время публикации'),
        ),
    ]
