# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_auto_20180129_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othermenu',
            name='key',
        ),
        migrations.AddField(
            model_name='othermenu',
            name='type',
            field=models.SmallIntegerField(db_index=True, default=0, unique=True, verbose_name='Тип меню'),
            preserve_default=False,
        ),
    ]
