# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('content', '0017_auto_20180212_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmenu',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.Page', verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='itemmenu',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Гиперссылка'),
        ),
    ]
