# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('content', '0018_auto_20180212_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmenu',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='itemmenu',
            name='link',
        ),
        migrations.RemoveField(
            model_name='itemmenu',
            name='title',
        ),
        migrations.AddField(
            model_name='itemmenu',
            name='_icon',
            field=models.ForeignKey(blank=True, db_column='icon', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='itemmenu',
            name='_link',
            field=models.URLField(blank=True, db_column='link', null=True, verbose_name='Гиперссылка'),
        ),
        migrations.AddField(
            model_name='itemmenu',
            name='_title',
            field=models.CharField(blank=True, db_column='title', max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
