# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_auto_20180221_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmenu',
            name='_description',
            field=models.TextField(blank=True, db_column='description', max_length=255, null=True, verbose_name='Описание'),
        ),
    ]
