# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_itemmenu__description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othermenu',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Главное боковое меню'), (1, 'Верхняя панель на главной'), (2, '')], db_index=True, unique=True, verbose_name='Тип меню'),
        ),
    ]
