# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0010_auto_20180221_1333'),
        ('content', '0028_auto_20180224_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleindex',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experts.ExpertPage', verbose_name='Страница эксперта'),
        ),
    ]
