# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_articleindex_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleindex',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_article_rubrics', to='experts.ExpertPage', verbose_name='Страница эксперта'),
        ),
    ]
