# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_auto_20180404_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuepage',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата/время публикации'),
        ),
    ]
