# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_issuepage_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuepage',
            name='published_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата/время публикации'),
        ),
    ]
