# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('content', '0034_auto_20180405_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuepage',
            name='cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image', verbose_name='Обложка журнала'),
        ),
    ]
