# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-06 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_auto_20180406_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='place',
            field=models.CharField(max_length=500, null=True, verbose_name='Место проведения'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='price',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Стоимость участия'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='active_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время конца'),
        ),
    ]
