# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-06 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_auto_20180406_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventindex',
            options={'verbose_name': 'События', 'verbose_name_plural': 'События'},
        ),
    ]
