# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-06 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('content', '0039_auto_20180406_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageExtraFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_fields', to='wagtailcore.Page')),
            ],
        ),
    ]
