# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-06 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_pageextrafields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageextrafields',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra_fields', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='pageextrafields',
            name='published_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
