# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-09 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0041_auto_20180406_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageextrafields',
            name='allowed_comments',
            field=models.BooleanField(default=True, verbose_name='Включить комментарии'),
        ),
        migrations.AddField(
            model_name='pageextrafields',
            name='show_in_news',
            field=models.BooleanField(default=False, verbose_name='Отображать в новостях'),
        ),
        migrations.AddField(
            model_name='pageextrafields',
            name='show_in_promo',
            field=models.BooleanField(default=False, verbose_name='Отображать в promotion'),
        ),
    ]
