# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0042_auto_20180409_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageextrafields',
            name='page',
        ),
        migrations.DeleteModel(
            name='PageExtraFields',
        ),
    ]
