# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0045_auto_20180412_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleindex',
            name='preview_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.CustomImage', verbose_name='Основная иллюстрация'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='preview_picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.CustomImage', verbose_name='Основная иллюстрация'),
        ),
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.CustomImage', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='preview_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.CustomImage', verbose_name='Основная иллюстрация'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='preview_picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.CustomImage', verbose_name='Основная иллюстрация'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='preview_picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.CustomImage', verbose_name='Основная иллюстрация'),
        ),
        migrations.AlterField(
            model_name='issuepage',
            name='cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.CustomImage', verbose_name='Обложка журнала'),
        ),
        migrations.AlterField(
            model_name='itemmenu',
            name='_icon',
            field=models.ForeignKey(blank=True, db_column='icon', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.CustomImage', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='preview_picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.CustomImage', verbose_name='Основная иллюстрация'),
        ),
    ]
