# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0046_auto_20180412_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='published_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата/время публикации'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='published_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата/время публикации'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='published_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата/время публикации'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='published_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата/время публикации'),
        ),
    ]
