# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0047_auto_20180412_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='mark',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Специальная метка'),
        ),
    ]
