# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_eventpage_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='place',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Место проведения'),
        ),
    ]
