# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0050_auto_20180424_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuepage',
            name='issue_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата выхода номера'),
        ),
    ]
