# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0051_issuepage_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuepage',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
