# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0053_articlepage_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='content.IssuePage', verbose_name='Выпуск журнала'),
        ),
    ]
