# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0055_auto_20180425_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='full_lead',
            field=models.TextField(blank=True, help_text='До 500 символов', max_length=500, null=True, verbose_name='Полный лид'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='full_lead',
            field=models.TextField(blank=True, help_text='До 500 символов', max_length=500, null=True, verbose_name='Полный лид'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='full_lead',
            field=models.TextField(blank=True, help_text='До 500 символов', max_length=500, null=True, verbose_name='Полный лид'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='full_lead',
            field=models.TextField(blank=True, help_text='До 500 символов', max_length=500, null=True, verbose_name='Полный лид'),
        ),
    ]
