# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0064_auto_20180622_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='До 60 символов', max_length=60, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='До 60 символов', max_length=60, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='До 60 символов', max_length=60, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='До 60 символов', max_length=60, null=True, verbose_name='Подзаголовок'),
        ),
    ]
