# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-03 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0069_auto_20180903_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='show_in_promo_widget',
            field=models.BooleanField(default=True, help_text='Действует если статья имеет рубрику promotion или галочку "Отображать в рубрике promotion"', verbose_name='Отображать в виджете promotion'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='show_in_promo_widget',
            field=models.BooleanField(default=True, help_text='Действует если статья имеет рубрику promotion или галочку "Отображать в рубрике promotion"', verbose_name='Отображать в виджете promotion'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='show_in_promo_widget',
            field=models.BooleanField(default=True, help_text='Действует если статья имеет рубрику promotion или галочку "Отображать в рубрике promotion"', verbose_name='Отображать в виджете promotion'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='show_in_promo_widget',
            field=models.BooleanField(default=True, help_text='Действует если статья имеет рубрику promotion или галочку "Отображать в рубрике promotion"', verbose_name='Отображать в виджете promotion'),
        ),
    ]
