# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-12 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0070_auto_20180903_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='has_adult_content',
            field=models.BooleanField(default=False, verbose_name='Контент 18+'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='has_adult_content',
            field=models.BooleanField(default=False, verbose_name='Контент 18+'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='has_adult_content',
            field=models.BooleanField(default=False, verbose_name='Контент 18+'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='has_adult_content',
            field=models.BooleanField(default=False, verbose_name='Контент 18+'),
        ),
    ]
