# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-10 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0072_auto_20180913_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='exclude_from_dzen_feed',
            field=models.BooleanField(default=False, verbose_name='Исключить из фида Яндекс.Дзен'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='exclude_from_dzen_feed',
            field=models.BooleanField(default=False, verbose_name='Исключить из фида Яндекс.Дзен'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='exclude_from_dzen_feed',
            field=models.BooleanField(default=False, verbose_name='Исключить из фида Яндекс.Дзен'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='exclude_from_dzen_feed',
            field=models.BooleanField(default=False, verbose_name='Исключить из фида Яндекс.Дзен'),
        ),
    ]
