# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-24 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0072_auto_20180913_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='SpecialTagFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Поиск по статьям', max_length=250, verbose_name='Заголовок фильтра')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание')),
                ('group_default_title', models.CharField(default='Выберите группу', max_length=250, verbose_name='Заголовок группы тегов')),
                ('tag_default_title', models.CharField(default='Выберите тег', max_length=250, verbose_name='Заголовок тегов')),
            ],
            options={
                'verbose_name': 'Фильтр',
                'verbose_name_plural': 'Фильтры',
            },
        ),
        migrations.CreateModel(
            name='SpecialTagGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название группы')),
                ('rubrics', models.ManyToManyField(related_name='special_tag_groups', to='content.ArticleIndex', verbose_name='Рубрики')),
            ],
            options={
                'verbose_name': 'Группа тегов',
                'verbose_name_plural': 'Группы тегов',
            },
        ),
        migrations.AddField(
            model_name='specialtagfilter',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='filters', to='content.SpecialTagGroup', verbose_name='Группы тегов'),
        ),
        migrations.AddField(
            model_name='specialtagfilter',
            name='rubric',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_tag_filter', to='content.ArticleIndex', verbose_name='Рубрика'),
        ),
        migrations.AddField(
            model_name='specialtag',
            name='group',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='content.SpecialTagGroup', verbose_name='Группа'),
        ),
    ]
