# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-21 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0072_auto_20180913_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='generate_og_preview_picture',
            field=models.BooleanField(default=True, verbose_name='Использовать сгенерированную картинку-превью для OpenGraph'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='generated_og_preview_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='generate_og_preview_picture',
            field=models.BooleanField(default=True, verbose_name='Использовать сгенерированную картинку-превью для OpenGraph'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='generated_og_preview_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='generate_og_preview_picture',
            field=models.BooleanField(default=True, verbose_name='Использовать сгенерированную картинку-превью для OpenGraph'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='generated_og_preview_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='newspage',
            name='generate_og_preview_picture',
            field=models.BooleanField(default=True, verbose_name='Использовать сгенерированную картинку-превью для OpenGraph'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='generated_og_preview_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
