# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-24 18:04
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0073_auto_20180924_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='special_tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='articles', to='content.SpecialTag', verbose_name='Специальные теги'),
        ),
    ]
