# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-21 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0073_auto_20180921_1221'),
        ('content', '0073_auto_20180921_0952'),
        ('content', '0073_auto_20180921_0954'),
    ]

    operations = [
    ]
