# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-18 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0073_auto_20181010_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='exclude_from_dzen_feed',
            field=models.BooleanField(default=False, verbose_name='Исключить материал из Яндекс.Дзен'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='exclude_from_dzen_feed',
            field=models.BooleanField(default=False, verbose_name='Исключить материал из Яндекс.Дзен'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='exclude_from_dzen_feed',
            field=models.BooleanField(default=False, verbose_name='Исключить материал из Яндекс.Дзен'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='exclude_from_dzen_feed',
            field=models.BooleanField(default=False, verbose_name='Исключить материал из Яндекс.Дзен'),
        ),
    ]
