# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-24 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0074_articlepage_special_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialtaggroup',
            name='rubrics',
        ),
    ]
