# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0074_merge_20180921_1307'),
        ('content', '0075_remove_specialtaggroup_rubrics'),
    ]

    operations = [
    ]
