# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-29 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0074_auto_20181018_1322'),
        ('content', '0076_merge_20180925_1438'),
    ]

    operations = [
    ]
