# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-15 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0079_auto_20181114_1820'),
        ('content', '0080_auto_20181107_1818'),
        ('content', '0079_auto_20181106_1443'),
    ]

    operations = [
    ]
